// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AspnetCoreMvcFull.Models
{
    public partial class GetMenuItemResult
    {
        public int id { get; set; }
        public string name { get; set; }
        public string nameLink { get; set; }
        public string icon { get; set; }
        public byte? sort { get; set; }
        public string sumcss { get; set; }
        public string subname { get; set; }
        public string nameclass { get; set; }
        public string namehref { get; set; }
    }
}
