// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AspnetCoreMvcFull.Models
{
    public partial class GetSubMenuItemResult
    {
        public int id { get; set; }
        public string name { get; set; }
        public int? moduleid { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public byte? sort { get; set; }
        public string subnameclass { get; set; }
        public string namelink { get; set; }
    }
}
