// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspnetCoreMvcFull.Models;

public partial class Menu
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? Moduleid { get; set; }

    public string Controller { get; set; }

    public string Action { get; set; }

    public byte? Sort { get; set; }

    public virtual Module Module { get; set; }
}