// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspnetCoreMvcFull.Models;

public partial class Module
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string NameLink { get; set; }

    public string Icon { get; set; }

    public byte? Sort { get; set; }

    public string Sumcss { get; set; }

    public string Subname { get; set; }

    public string Nameclass { get; set; }

    public string Namehref { get; set; }

    public virtual ICollection<Menu> Menus { get; set; } = new List<Menu>();
}